name = "mtcacg-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

# ⚠️ 注意：填入你的数据库绑定信息 (和原来 worker 里的配置一样)
[[d1_databases]]
binding = "DB"  #这个不能改，写死
database_name = "myblove"   # 随意即可
database_id = "18c655b1-fab6-4548-9b8f-072982ba195f"  #例：5a6xxxf53-3xxx-470c-b8d4-dxxxxxxaf30e
